#!/bin/bash
# monitor directory and split files with spleeter (deezer).
# v 0.2
# (c) kamilbaranski.com

# set the parent directory, where {2,4,5}stems directories will be created & monitored.
GLOBAL_SMD_PATH="/home/kb/spleeter"


spleeter_monitor_directory() {
    STEMS="$1"

    MONITOR_DIRECTORY="${GLOBAL_SMD_PATH}/${STEMS}stems"
    TXT="${STEMS} stems"
    MODEL="spleeter:${STEMS}stems-16kHz"
    OUTPUT_SUBDIRECTORY="output"
    OUTPUT_DIRECTORY="${MONITOR_DIRECTORY}/{OUTPUT_SUBDIRECTORY}"
    LOGNAME="[spleeter_monitor_dir:]"

    mkdir -p "$MONITOR_DIRECTORY"

    echo "${LOGNAME} Monitoring '$MONITOR_DIRECTORY' directory."

    inotifywait -m "$MONITOR_DIRECTORY" -e close_write -e moved_to | while read NEVERMIND ACTION FILENAME; do
        echo "${LOGNAME} $FILENAME appeared in ${MONITOR_DIRECTORY}. Spleeting $TXT..."
        spleeter separate -p $MODEL -o "$MONITOR_DIRECTORY" -f "${OUTPUT_SUBDIRECTORY}/{filename}_{instrument}.{codec}" "${MONITOR_DIRECTORY}/${FILENAME}"
        echo "${LOGNAME} $FILENAME spleeting finished."
    done
}

case "$1" in
    2)
        spleeter_monitor_directory 2
        ;;
    4)
        spleeter_monitor_directory 4
        ;;
    5)
        spleeter_monitor_directory 5
        ;;
    *)
        echo "Usage: spleeter_monitor_directory nos"
        echo "  where nos is number of stems (2, 4 or 5)"
        exit 1
esac
